plugins {
    id 'java'
    id 'war'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Spring MVC
    implementation 'org.springframework:spring-webmvc:6.2.10'

    // Jakarta Servlet - Tomcat 10.1
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    // JSP
    compileOnly 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1'

    // JSTL
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}